/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "bwolnfdhnnflinvipnvs"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3b2xuZmRobm5mbGludmlwbnZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA1ODEwMjYsImV4cCI6MjEwNjE1NzAyNn0.zBO4-jW9PpWihmPgTc4OXWyXg-hwGpUTUGk8JjrGqN8"